### ISSUE TITLE
DT: Disable i2c0

### ISSUE THREAD

**Issue by lategoodbye** [lategoodbye/rpi-zero#22]
The GPU firmware of the Raspberry Pi 3 uses i2c0 to communicate to the FXL6408 gpio expander. It is a bad idea to also use this interface from the ARM side. So avoid any conflict by disabling it.

Please look at https://github.com/anholt/linux/issues/89 for any further details.

**Comment by 6by9** [comment]
I was just casting an eye over open issues here.

The firmware hasn't used BSC0 for the GPIO expander and SMPS since Jan 2017.
We're now relying on using BSC0 from the kernel for libcamera and driving the DSI touchscreen through the DRM subsystem.
