### ISSUE TITLE
mt7610u: Wifi driver doesn't probe properly

### ISSUE THREAD

**Issue by lategoodbye** [lategoodbye/rpi-zero#41]
Connecting the TP-Link Archer T2UH to a Raspberry Pi 3 doesn't result a properly probing driver.

https://marc.info/?l=linux-wireless&m=154875316703367&w=2
https://marc.info/?l=linux-wireless&m=154971413730974
https://github.com/raspberrypi/linux/issues/2817

**Comment by lategoodbye** [comment]
This issue should be fixed with release of 5.1-rc1

**Comment by nullr0ute** [comment]
@lategoodbye would you happen to have reference to the upstream fix, I've also had people report bugs for that one

**Comment by lategoodbye** [comment]
The mt76 driver is under heavy development, so backport would be hard.
This was the series:
https://patchwork.kernel.org/cover/10807911/
