### ISSUE TITLE
Measure and fix poll rate of raspberrypi-ts

### ISSUE THREAD

**Issue by lategoodbye** [lategoodbye/rpi-zero#45]
Recent [issue](https://github.com/raspberrypi/linux/issues/3227) in downstream shows a timing issue in polling behavior. As far i can see, this issue still persists in upstream, but the solution might be different.

**Comment by lategoodbye** [comment]
@vianpl Could you please give me some hints to test the raspberrypi-ts (especially to wiring and devicetree)?

**Comment by vianpl** [comment]
Hi @lategoodbye!

As far as raspberrypi-ts.c is concerned you can't do much to fix this issue. The firmware mandates the polling rate and that's the faster it'll ever be. IIRC the kernel driver uses the same polling frequency as the one downstream. Which, I assume, is adapted to the firmware's polling speed. To test it just  connect the ribbon cable, power and ground then follow Documentation/devicetree/bindings/input/touchscreen/raspberrypi,firmware-ts.txt.


If you want to use the I2C0 bus directly with upstream, bypassing the firmware, then you theoretically could get faster speeds. No need to change the wiring, though there are several issues:
- I2C0 is a bus used by the firmware not only for the touchscreen but for a lot of other peripherals. So disabling the touch poll thread in the firmware is not an all around solution. I asked the foundation to do something about it (https://github.com/raspberrypi/firmware/issues/1138).
- The non firmware based upstream driver (edt-ft5x06.c) has no polling support, and the touchscreen doesn't generate interrupts. I sent a patch addressing this some time ago, but it got ignored and I forgot about it (https://lkml.org/lkml/2019/4/30/1099). I could review it and re-send it if you see any use for it.

**Comment by lategoodbye** [comment]
It seems that there is still an [issue](https://github.com/raspberrypi/linux/issues/3777#issuecomment-1090823272) with the polling rate.

**Comment by lategoodbye** [comment]
Close this, because the non-firmware driver edt-ft5x06 is the right way tm
